import { NextResponse } from "next/server";
import type { LetterStatus } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { currentUserOrDemo } from "@/lib/session";
import { decryptText } from "@/lib/docCrypto";
import { recordKaiEvent } from "@/lib/kaiEvents";
import { track, PRODUCT_EVENTS } from "@/lib/events";

export const dynamic = "force-dynamic";

// Return a letter to the client with its at-rest-encrypted fields decrypted.
function decryptedLetter<
  T extends { body: string; responseText: string | null; responseAnalysis: string | null }
>(l: T): T {
  return {
    ...l,
    body: decryptText(l.body),
    responseText: l.responseText ? decryptText(l.responseText) : l.responseText,
    responseAnalysis: l.responseAnalysis ? decryptText(l.responseAnalysis) : l.responseAnalysis,
  };
}

const VALID_STATUSES: LetterStatus[] = [
  "DRAFT",
  "GENERATED",
  "PRINTED",
  "MAILED",
  "RESPONSE_RECEIVED",
  "RESOLVED",
];

// Fetch a single letter (used by the print view).
export async function GET(_req: Request, { params }: { params: { id: string } }) {
  const user = await currentUserOrDemo();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const letter = await prisma.letter.findFirst({
    where: { id: params.id, userId: user.id },
  });
  if (!letter) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json({ letter: decryptedLetter(letter) });
}

// Deletes one of the user's letters (e.g. generated by mistake).
export async function DELETE(_req: Request, { params }: { params: { id: string } }) {
  const user = await currentUserOrDemo();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const existing = await prisma.letter.findFirst({ where: { id: params.id, userId: user.id } });
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });

  await prisma.letter.delete({ where: { id: existing.id } });
  return NextResponse.json({ ok: true });
}

// Update a letter's status (e.g. mark MAILED / RESPONSE_RECEIVED / RESOLVED).
// Advancing to MAILED stamps mailedAt and, if the dispute resolved, flips the
// related tradeline to resolved so dashboards reconcile.
export async function PATCH(req: Request, { params }: { params: { id: string } }) {
  const user = await currentUserOrDemo();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json().catch(() => ({}));
  const status = body?.status as LetterStatus | undefined;
  if (!status || !VALID_STATUSES.includes(status)) {
    return NextResponse.json({ error: "Invalid status" }, { status: 400 });
  }

  const existing = await prisma.letter.findFirst({ where: { id: params.id, userId: user.id } });
  if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const letter = await prisma.letter.update({
    where: { id: existing.id },
    data: {
      status,
      ...(status === "MAILED" && !existing.mailedAt ? { mailedAt: new Date() } : {}),
    },
  });

  if (status === "MAILED" && !existing.mailedAt) {
    await recordKaiEvent(user.id, "letter.mailed", {
      refType: "letter",
      refId: letter.id,
      payload: { recipient: existing.recipientName, round: existing.round },
    });
  }

  // When a dispute is marked RESOLVED, reflect that on the tradeline.
  if (status === "RESOLVED" && existing.tradelineId) {
    await prisma.tradeline.update({
      where: { id: existing.tradelineId },
      data: { resolved: true },
    });
    await recordKaiEvent(user.id, "dispute.resolved", {
      refType: "tradeline",
      refId: existing.tradelineId,
      payload: { recipient: existing.recipientName, round: existing.round },
    });
  }

  // Only on the actual transition into RESOLVED — re-PATCHing an already-resolved
  // letter must not inflate the funnel metric.
  if (status === "RESOLVED" && existing.status !== "RESOLVED") {
    await track(PRODUCT_EVENTS.disputeCompleted, { userId: user.id, meta: { round: existing.round } });
  }

  return NextResponse.json({ ok: true, letter: decryptedLetter(letter) });
}
